/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.androidsoft.games.slowit;

public final class R {
    public static final class anim {
        public static final int fade=0x7f040000;
        public static final int layout_random_fade=0x7f040001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int background=0x7f020000;
        public static final int ball=0x7f020001;
        public static final int button_1star=0x7f020002;
        public static final int button_2stars=0x7f020003;
        public static final int button_3stars=0x7f020004;
        public static final int button_locked=0x7f020005;
        public static final int button_new=0x7f020006;
        public static final int icon=0x7f020007;
        public static final int icon_hiscore=0x7f020008;
        public static final int icon_level_done=0x7f020009;
        public static final int shape=0x7f02000a;
        public static final int splash=0x7f02000b;
    }
    public static final class id {
        public static final int button_play=0x7f060006;
        public static final int image_splash=0x7f060004;
        public static final int level_grid1=0x7f060001;
        public static final int level_grid2=0x7f060002;
        public static final int level_scrollview=0x7f060000;
        public static final int splash=0x7f060003;
        public static final int text=0x7f060005;
    }
    public static final class layout {
        public static final int level_selector=0x7f030000;
        public static final int splash=0x7f030001;
    }
    public static final class string {
        public static final int activity_title=0x7f050001;
        public static final int app_name=0x7f050000;
        public static final int button_play=0x7f050004;
        public static final int first_run_dialog_message=0x7f050008;
        /**  What's new dialog 
         */
        public static final int first_run_dialog_title=0x7f050007;
        public static final int label_level=0x7f050016;
        public static final int label_remaining_time=0x7f050015;
        public static final int label_score=0x7f050017;
        public static final int message_game_over=0x7f050012;
        public static final int message_hiscore=0x7f050014;
        public static final int message_level_done=0x7f05000c;
        public static final int message_level_failed=0x7f05000f;
        public static final int new_game=0x7f050002;
        public static final int next_level=0x7f05000d;
        public static final int ok=0x7f050006;
        public static final int quit=0x7f050003;
        public static final int redo_level=0x7f050010;
        public static final int title_game_over=0x7f050011;
        public static final int title_hiscore=0x7f050013;
        public static final int title_level_done=0x7f05000b;
        public static final int title_level_failed=0x7f05000e;
        public static final int version=0x7f050005;
        public static final int whats_new_dialog_message=0x7f05000a;
        public static final int whats_new_dialog_title=0x7f050009;
    }
}
